Warn about outdated content & misc. housekeeping
KeYProject/key-docs pull request #14
Opened 2023-10-24 17:02 UTC by FliegendeWurst

- Warning labels for outdated pages
- Changelog for 2.12.1
- Hidden page (#12) added to navigation
- Duplicate HowtoTaclet removed

2023-10-24 18:10 UTC, FliegendeWurst commented on mkdocs.yml
> +        - devel/NewKeyParser.md
Related: #12

2023-11-21 16:09 UTC, WolframPfeifer requested changes
Thanks for updates and clean-up!

I think we should keep the old documentation for now (How2ExtRecoder), as Recoder is still part of the project and the documentation might still be helpful for understanding it. I do not know if we have it somewhere else.

Maybe it would also make sense to move the caching documentation to a different PR, since I do not want to have it in the docs until it is actually implemented in KeY that way ...

2023-11-21 16:09 UTC, WolframPfeifer commented on pyproject.toml
What is this file used for?

2023-11-23 09:36 UTC, FliegendeWurst commented on pyproject.toml
It specifies the dependencies required by mkdocs. Some new dependency management tools for Python can use this file to automatically set up a dev environment.

But it would certainly be a good idea to unify the dependency info. I think there are at least three different places they are specified at the moment..

2023-11-23 12:28 UTC, merged